# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='Monitor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\x12\x07Monitor\"#\n\x0eMonitorRequest\x12\x11\n\toperation\x18\x01 \x01(\x08\"-\n\x0bMonitorData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"D\n\x0eMonitorSummary\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"2\n\x10MonitorOperation\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\x05\x32\xf0\x01\n\x0eMonitorService\x12\x45\n\x10PutMonitorStream\x12\x17.Monitor.MonitorRequest\x1a\x14.Monitor.MonitorData\"\x00\x30\x01\x12G\n\x11PutMonitorSummary\x12\x17.Monitor.MonitorRequest\x1a\x17.Monitor.MonitorSummary\"\x00\x12N\n\x12GetOperationStream\x12\x17.Monitor.MonitorRequest\x1a\x19.Monitor.MonitorOperation\"\x00(\x01\x30\x01\x62\x06proto3'
)




_MONITORREQUEST = _descriptor.Descriptor(
  name='MonitorRequest',
  full_name='Monitor.MonitorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Monitor.MonitorRequest.operation', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=61,
)


_MONITORDATA = _descriptor.Descriptor(
  name='MonitorData',
  full_name='Monitor.MonitorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Monitor.MonitorData.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Monitor.MonitorData.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=108,
)


_MONITORSUMMARY = _descriptor.Descriptor(
  name='MonitorSummary',
  full_name='Monitor.MonitorSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='Monitor.MonitorSummary.start_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='Monitor.MonitorSummary.end_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Monitor.MonitorSummary.data', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=178,
)


_MONITOROPERATION = _descriptor.Descriptor(
  name='MonitorOperation',
  full_name='Monitor.MonitorOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='Monitor.MonitorOperation.mode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interval', full_name='Monitor.MonitorOperation.interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['MonitorRequest'] = _MONITORREQUEST
DESCRIPTOR.message_types_by_name['MonitorData'] = _MONITORDATA
DESCRIPTOR.message_types_by_name['MonitorSummary'] = _MONITORSUMMARY
DESCRIPTOR.message_types_by_name['MonitorOperation'] = _MONITOROPERATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitorRequest = _reflection.GeneratedProtocolMessageType('MonitorRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONITORREQUEST,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorRequest)
  })
_sym_db.RegisterMessage(MonitorRequest)

MonitorData = _reflection.GeneratedProtocolMessageType('MonitorData', (_message.Message,), {
  'DESCRIPTOR' : _MONITORDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorData)
  })
_sym_db.RegisterMessage(MonitorData)

MonitorSummary = _reflection.GeneratedProtocolMessageType('MonitorSummary', (_message.Message,), {
  'DESCRIPTOR' : _MONITORSUMMARY,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorSummary)
  })
_sym_db.RegisterMessage(MonitorSummary)

MonitorOperation = _reflection.GeneratedProtocolMessageType('MonitorOperation', (_message.Message,), {
  'DESCRIPTOR' : _MONITOROPERATION,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorOperation)
  })
_sym_db.RegisterMessage(MonitorOperation)



_MONITORSERVICE = _descriptor.ServiceDescriptor(
  name='MonitorService',
  full_name='Monitor.MonitorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=233,
  serialized_end=473,
  methods=[
  _descriptor.MethodDescriptor(
    name='PutMonitorStream',
    full_name='Monitor.MonitorService.PutMonitorStream',
    index=0,
    containing_service=None,
    input_type=_MONITORREQUEST,
    output_type=_MONITORDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutMonitorSummary',
    full_name='Monitor.MonitorService.PutMonitorSummary',
    index=1,
    containing_service=None,
    input_type=_MONITORREQUEST,
    output_type=_MONITORSUMMARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOperationStream',
    full_name='Monitor.MonitorService.GetOperationStream',
    index=2,
    containing_service=None,
    input_type=_MONITORREQUEST,
    output_type=_MONITOROPERATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITORSERVICE)

DESCRIPTOR.services_by_name['MonitorService'] = _MONITORSERVICE

# @@protoc_insertion_point(module_scope)
