# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import monitor_pb2 as monitor__pb2


class MonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRealTimeImage = channel.unary_unary(
                '/Monitor.Monitor/GetRealTimeImage',
                request_serializer=monitor__pb2.MonitorRequest.SerializeToString,
                response_deserializer=monitor__pb2.MonitorData.FromString,
                )
        self.PutMonitorStream = channel.stream_stream(
                '/Monitor.Monitor/PutMonitorStream',
                request_serializer=monitor__pb2.MonitorData.SerializeToString,
                response_deserializer=monitor__pb2.MonitorReply.FromString,
                )


class MonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRealTimeImage(self, request, context):
        """For server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutMonitorStream(self, request_iterator, context):
        """The monitor is in local network, and put the monitor stream to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRealTimeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealTimeImage,
                    request_deserializer=monitor__pb2.MonitorRequest.FromString,
                    response_serializer=monitor__pb2.MonitorData.SerializeToString,
            ),
            'PutMonitorStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PutMonitorStream,
                    request_deserializer=monitor__pb2.MonitorData.FromString,
                    response_serializer=monitor__pb2.MonitorReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Monitor.Monitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRealTimeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monitor.Monitor/GetRealTimeImage',
            monitor__pb2.MonitorRequest.SerializeToString,
            monitor__pb2.MonitorData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutMonitorStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Monitor.Monitor/PutMonitorStream',
            monitor__pb2.MonitorData.SerializeToString,
            monitor__pb2.MonitorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
