# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='Monitor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\x12\x07Monitor\".\n\x0bMonitorData\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"!\n\x0eMonitorRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1d\n\x0cMonitorReply\x12\r\n\x05reply\x18\x01 \x01(\x05\x32\x95\x01\n\x07Monitor\x12\x43\n\x10GetRealTimeImage\x12\x17.Monitor.MonitorRequest\x1a\x14.Monitor.MonitorData\"\x00\x12\x45\n\x10PutMonitorStream\x12\x14.Monitor.MonitorData\x1a\x15.Monitor.MonitorReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_MONITORDATA = _descriptor.Descriptor(
  name='MonitorData',
  full_name='Monitor.MonitorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Monitor.MonitorData.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Monitor.MonitorData.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=72,
)


_MONITORREQUEST = _descriptor.Descriptor(
  name='MonitorRequest',
  full_name='Monitor.MonitorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='Monitor.MonitorRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=107,
)


_MONITORREPLY = _descriptor.Descriptor(
  name='MonitorReply',
  full_name='Monitor.MonitorReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='Monitor.MonitorReply.reply', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['MonitorData'] = _MONITORDATA
DESCRIPTOR.message_types_by_name['MonitorRequest'] = _MONITORREQUEST
DESCRIPTOR.message_types_by_name['MonitorReply'] = _MONITORREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitorData = _reflection.GeneratedProtocolMessageType('MonitorData', (_message.Message,), {
  'DESCRIPTOR' : _MONITORDATA,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorData)
  })
_sym_db.RegisterMessage(MonitorData)

MonitorRequest = _reflection.GeneratedProtocolMessageType('MonitorRequest', (_message.Message,), {
  'DESCRIPTOR' : _MONITORREQUEST,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorRequest)
  })
_sym_db.RegisterMessage(MonitorRequest)

MonitorReply = _reflection.GeneratedProtocolMessageType('MonitorReply', (_message.Message,), {
  'DESCRIPTOR' : _MONITORREPLY,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:Monitor.MonitorReply)
  })
_sym_db.RegisterMessage(MonitorReply)



_MONITOR = _descriptor.ServiceDescriptor(
  name='Monitor',
  full_name='Monitor.Monitor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=141,
  serialized_end=290,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRealTimeImage',
    full_name='Monitor.Monitor.GetRealTimeImage',
    index=0,
    containing_service=None,
    input_type=_MONITORREQUEST,
    output_type=_MONITORDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PutMonitorStream',
    full_name='Monitor.Monitor.PutMonitorStream',
    index=1,
    containing_service=None,
    input_type=_MONITORDATA,
    output_type=_MONITORREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITOR)

DESCRIPTOR.services_by_name['Monitor'] = _MONITOR

# @@protoc_insertion_point(module_scope)
